### ISSUE TITLE
[BUG] 'cx configure' utility broken in Mac

### ISSUE THREAD

**Issue by yangsec888** [Checkmarx/ast-cli#331]
### Describe the bug
The mac cli configure utility is broken

### Expected behavior
$ cx configure  <---enter user params here
$ cx configure show --> show save user params here

### Actual behavior
$ cx configure show --> return empty line

### Steps to reproduce
1. git clone the project in a Macbook (amd64)
2. follow go build procedure
3.  add the compiled binary path into the shell $PATH
4. execute the command '$ cx configure' per quickstart document: https://checkmarx.atlassian.net/wiki/spaces/AST/pages/3080487576/CxAST+CLI+Quick+Start+Guide
5. execute the command '$ cx configure show' per document: https://checkmarx.atlassian.net/wiki/spaces/AST/pages/6046941983/configure+show

### Environment
- CLI version:    $ cx version --> 'dev' as of Jan 18 2021
- Platform (e.g. Windows 10 x64):  MacOX amd64

### Logs
Paste the output from your CLI. Redact if needed.

**Comment by pedrompflopes** [comment]
@yangsec888 Thanks for pointing this out. The folder permissions were not correct. We fixed it in #333.
