### ISSUE TITLE
[REQ] 'cx result' support additional filter type 'state'

### ISSUE THREAD

**Issue by yangsec888** [Checkmarx/ast-cli#336]
### Is your request related to a workflow problem?
Yes. Once the scan data is validated by our analysts, it would be marked as 'Confirmed', then be dumped out into the json file. The additional filter will allow data filtering with a 'state' of 'CONFIRMED'. In order to support this workflow, a new filter type by 'state' could be built-into the sub-command.

### Propose a solution
Support the result data filter by type 'state', such as below data flow:
>>> import json
>>> f=open("./cx_result.json","r")
>>> data=json.load(f)
>>> results=data['results']
>>> results_conf = filter(lambda x: x['state']=='CONFIRMED', results)
>>> print(list(results_conf))
[{'type': 'sast', 'id': '0', 'similarityId': '-1627780850', 'status': 'NEW', 'state': 'CONFIRMED', ...}}]

### Additional comments
Refer to the '--filter <string>' flag section in the current implementation document here: https://checkmarx.atlassian.net/wiki/spaces/AST/pages/6025740424/result#Flags

**Comment by jbrotsos** [comment]
Planning this for the short-term roadmap (early April)

**Comment by yangsec888** [comment]
@jbrotsos Thanks for the quick response. Happy coding!
