### ISSUE TITLE
[BUG] files or folders params seem to not working

### ISSUE THREAD

**Issue by alex46300** [Checkmarx/ast-cli#354]
### Describe the bug
When I launch a new scan, --file-filter param does not work for exclude files or folders

### Steps to reproduce
I made some tests with CLI tool. I tried :

`cx.exe scan create --project-name bodgeit -s https://github.com/psiinon/bodgeit.git --sast-preset-name "High and Medium" --file-filter "!test/,!advanced.jsp,!advanced.js" --branch "master" --debug`

or

`cx.exe scan create --project-name bodgeit -s https://github.com/psiinon/bodgeit.git --sast-preset-name "High and Medium" --file-filter "!test/,!advanced.jsp,!advanced.js,!root,!src" --branch "master" --debug`

or

`cx.exe scan create --project-name bodgeit -s https://github.com/psiinon/bodgeit.git --sast-preset-name "High and Medium" --file-filter "!test/,!advanced.jsp,!advanced.js,!root/*,!src/*" --branch "master" --debug`

### Environment
- CLI version : 2.0.12
- Platform : Windows 10 x64

### Additional comments
Whit or without folders/files exclusions the number of vulnerabilities is always the same

### Logs

`2022/02/22 17:29:10 Connected completed in: 156 (ms)

         Created At: 2022-02-22, 16:26:53
               Risk: High Risk
         Project ID: 3f72e3d2-2f2f-467f-a9b1-d5820e2c9e40
            Scan ID: 0f309a66-3a08-4df6-8348-2b90cf08c0ec
       Total Issues: 168
        High Issues: 70
      Medium Issues: 91
         Low Issues: 7
        Kics Issues: 3
      CxSAST Issues: 152
       CxSCA Issues: 13`

**Comment by pedrompflopes** [comment]
Hi @alex46300  

Thanks for raising this. 

The -file-filter flag only works if you use a source directory. 

`cx.exe scan create --project-name bodgeit -s . --sast-preset-name "High and Medium" --file-filter "!test,!advanced.jsp,!advanced.js,!root,!src" --branch "master" --debug`

We will update the documentation.

**Comment by alex46300** [comment]
Hello @pedrompflopes 

Thanks for your response but I don't really understand what do you mean about "use a source directory" ?
You mean I need to have the source at root folder localy and --file-filter does not work with github repository ?

Thanks

**Comment by pedrompflopes** [comment]
Yes @alex46300 
 
The "-s" (--file-source) needs to be a directory. Similar to the example below where the source is the current directory. 

`cx.exe scan create --project-name bodgeit -s . --sast-preset-name "High and Medium" --file-filter "!test,!advanced.jsp,!advanced.js,!root,!src" --branch "master" --debug`

**Comment by jbrotsos** [comment]
Hey @alex46300 , did @pedrompflopes suggestion work for you?
