### ISSUE TITLE
[REQ] Support Gitlab SAST output format (gl-sast-report.json)

### ISSUE THREAD

**Issue by ssavrim** [Checkmarx/ast-cli#538]
### Is your request related to a workflow problem?
In our gitlab projects we are integrating `ast-cli` in pipeline execution for SAST scanning in checkmarxOne.
In older versions of checkmarx, `cx-flow` provided an option to generate output format `gl-sast-report.json`.

Is it planned to support this output format with `ast-cli` ?

### Propose a solution
We tried to convert the existing `cx_result.json` into a compatible `gl-sast-report.json`, but some fields are missing to be compliant with the schema providen by Gitlab at https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/sast-report-format.json

### Additional comments
Here the link to gitlab documentation: https://docs.gitlab.com/ee/user/application_security/sast/#reports-json-format.

**Comment by Yoavast** [comment]
Hi @ssavrim 
Thank you for bringing this issue to our attention. We understand the importance of supporting the gl-sast-report.json output format with ast-cli for your GitLab projects' pipeline execution and SAST scanning in checkmarxOne.

While we currently have a fully packed development schedule for the rest of the year, we acknowledge  this request and will do our best to find a suitable solution.
Considering the impact we have assigned this issue a medium priority.

We appreciate your patience as we explore potential support.
If you have any additional information or insights that could assist us in resolving this matter, please feel free to share them

Regards,
Yoav Ast | CxONE Product Manager |

**Comment by ssavrim** [comment]
Hi @Yoavast,
Thanks for your feedback.
For the moment we wil try to extract needed data from existing output file `cx_results.json`

Regards,
