### ISSUE TITLE
[REQ] Get results from scan in CLI

### ISSUE THREAD

**Issue by MAP4H** [Checkmarx/ast-cli#541]
### Is your request related to a workflow problem?
I haven't found a way to pull all the scan results in one single request(I mean all the scan results from all the sast projects), is there any way to perform this? Something I´m missing? right now I have only found to export the results with ./cx results show --scan-id <scan ID>, but it is limited to one scan id at a time

### Additional comments
Would be nice to export all the project vulnerabilities in one request and export to json

**Comment by Yoavast** [comment]
Hi @MAP4H 
Thank you for reaching out and sharing your enhancement request. I understand that you are looking for a way to pull all the scan results from all the SAST projects in one single request. 

To provide you with the correct solution, I would like to clarify whether you are using Checkmarx One or CxSAST?
This is because you mentioned "the scan results from all the SAST projects." 
In Checkmarx One we do not have a base engine project type.

Yoav

**Comment by MAP4H** [comment]
> Hi @MAP4H Thank you for reaching out and sharing your enhancement request. I understand that you are looking for a way to pull all the scan results from all projects in one single request.
> 
> To provide you with the correct solution, I would like to clarify whether you are using Checkmarx One or CxSAST? This is because you mentioned "the scan results from all the SAST projects." In Checkmarx One we do not have a base engine project type.
> 
> Yoav

Hello, I´m using Checkmarx One, sorry for the confusion. I´m trying to find a way to get all the results trough the CLI. Any ideas?

**Comment by Yoavast** [comment]
> 


We currently do not have a dedicated command to retrieve all the results. However, this is something that we could consider adding to our CLI roadmap as we continue to enhance our platform's reporting capabilities.

To better assist you, it would be helpful to understand why you need to retrieve all the results in a single JSON file. 
Also, are you looking for a summary of the total number of results per project, or do you require detailed results for each issue?

In the meantime, as a workaround, you can create a script that gets a list of all scan IDs and then iterates through them using the ./cx results show --scan-id command. The script can aggregate all the JSON reports into a single file.

**Comment by jbrotsos** [comment]
Closing issue - this can be done with a script with the CLI as a wrapper:

1. Get list of projects
2. Get scan results for each projetct.
