### ISSUE TITLE
[BUG] Sarif file with the same HelpUri for all issues

### ISSUE THREAD

**Issue by gar0t0** [Checkmarx/ast-cli#544]
### Describe the bug
I don't know if it is a BUG or not.

I'm using the cx to export results and import in my DefectDojo, but the information in json is much more rich than sarif file.

When we open the sarif file, all helpUri are the same for all issues, and indicate a documentation of releases from CxOne.

That information isn't util for developers solve the problem.

### Expected behavior
Any help URL for solve the problem indicated in Checkmarx.

### Actual behavior
grep -i HelpUri teste.sarif                                                                         1 ↵
              "helpUri": "https://checkmarx.com/resource/documents/en/34965-67042-checkmarx-one.html",
              "helpUri": "https://checkmarx.com/resource/documents/en/34965-67042-checkmarx-one.html",
              "helpUri": "https://checkmarx.com/resource/documents/en/34965-67042-checkmarx-one.html",
              "helpUri": "https://checkmarx.com/resource/documents/en/34965-67042-checkmarx-one.html",
              "helpUri": "https://checkmarx.com/resource/documents/en/34965-67042-checkmarx-one.html",

### Steps to reproduce
cx results show --scan-id <scan-id> --report-format sarif

### Environment
- CLI version: 2.0.48
- Platform MacOS

### Additional comments
We need more information or an convert tool from json to sarif

**Comment by pedrompflopes** [comment]
Hi @gar0t0  

We added this to our backlog. Thanks.
