### ISSUE TITLE
[REQ] The PR decoration tool generates a new comment every time a new commit is made

### ISSUE THREAD

**Issue by rzandonai** [Checkmarx/ast-cli#580]
### Is your request related to a workflow problem?
The PR decoration tool generates a new comment every time a new commit is made to the pull request, which results in clutter. I would like the comment to be updated instead of generating a new one each time.

### Propose a solution
I propose that the PR decoration tool should be modified to update the existing comment when a new commit is made to the pull request, rather than creating a new comment for each commit.

### Additional comments
No additional comments at this time.

**Comment by jbrotsos** [comment]
@rzandonai Which Code Repo is this for (GH, GL, ADO, Bitbucket)? Are you using Webhook integration or a CLI command (i.e. GH Actions)?

**Comment by rzandonai** [comment]
Github,  CLI on a  Tekton pipeline

**Comment by pedrompflopes** [comment]
Hi @rzandonai  

Do you have a way to check the PR event action in tekton ? If no code changes were made the scan shouldn't be triggered at all.  

You could check the following status. 
"opened", "reopened", "synchronize"
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

Thanks.
