### ISSUE TITLE
[BUG] Contributor count breaks with an NPE when encountering an empty repo.

### ISSUE THREAD

**Issue by nleach999** [Checkmarx/ast-cli#592]
### Describe the bug
When running the contributor count utility, it throws an NPE when it encounters a repository that does not contain code.  The enumeration ends.

### Expected behavior
It should see the repo is empty and move on without stopping the enumeration.

### Actual behavior
While enumerating an org's repos, it encountered a repo with no code in it.  It threw an NPE and exited the program.

### Steps to reproduce

1. Use a GitHub org (it probably does the same in other SCMs, I only tried GitHub)
2. Create a new repository, don't add any files to it.
3. Run the contributor count tool to enumerate the org.

### Environment
CLI 2.0.58
Powershell on an unknown Windows version.

### Additional comments
N/A

### Logs
![image](https://github.com/Checkmarx/ast-cli/assets/29153509/46e174f9-4360-485b-9792-94e7a20bd257)

**Comment by pedrompflopes** [comment]
Hi @nleach999  
Thanks for raising the issue. We are currently fixing it under #599
