### ISSUE TITLE
[REQ] handle requirements.txt custom filenames

### ISSUE THREAD

**Issue by ArnaudLacroix** [Checkmarx/ast-cli#697]
### Is your request related to a workflow problem?
I have some python projects on which requirements.txt files can have variable names like requirement[custom string].txt. Today, the CLI filters them and they are excluded from the scan.

### Propose a solution
add "requirement*.txt" to the filters.

**Comment by jbrotsos** [comment]
Done, will be available in release 2.0.73
FYI, It will not solve AST filtering, only the Cli
