### ISSUE TITLE
[BUG] Report PDF Options - ScanSummary not working

### ISSUE THREAD

**Issue by gar0t0** [Checkmarx/ast-cli#703]
### Describe the bug
After this new version, the option to generate pdf reports from ScanSummary broke the scan.
This is afecting your product ast-github-actions too.

### Expected behavior
(...)
2024/04/09 16:37:15 Scan Finished with status:  Completed
            Scan Summary:
              Created At: 2024-04-09, 16:33:15
              Project Name: my-org/my-project
              Scan ID: 123456-cccc-aaa-bbb-abcdefghijk

### Actual behavior
2024/04/09 16:49:34 Scan status:  Running
2024/04/09 16:49:43 Scan Finished with status:  Completed
report option "scansummary" unavailable

### Steps to reproduce
Run an test and generate a report 

### Environment
- 2.0.72 (MacOS)
- ast-github-actions (Main)

### Logs
./cx scan create -s git@github.com:my-org/project --project-name my-org/projects -b feature/batata --ssh-key "/Users/user/.ssh/id_rsa" --scan-types sast,iac-security,sca --report-pdf-options Sast,Sca,Iac-Security,ScanSummary,ExecutiveSummary,ScanResults --report-format pdf
2024/04/09 16:47:04

Scanning branch feature/batata...

Scan ID      : <scan-id>
Project ID   : <project-id>
Project Name : my-org/project
Status       : Running
Created at   : 04-09-24
Branch       : feature/batata
Tags         : []
Type         : Full
Timeout      : NONE
Initiator    : my-user
Origin       : ASTCLI 2.0.72
Engines      : [ sast kics sca]

2024/04/09 16:47:05 Wait for scan to complete aaaaa-aaaa-aaaa-aaa-bbbbbbbbbb Running
2024/04/09 16:47:10 Scan status:  Running
2024/04/09 16:47:16 Scan status:  Running
2024/04/09 16:47:21 Scan status:  Running
2024/04/09 16:47:27 Scan status:  Running
2024/04/09 16:47:32 Scan status:  Running
2024/04/09 16:47:39 Scan status:  Running
2024/04/09 16:47:46 Scan status:  Running
2024/04/09 16:47:52 Scan status:  Running
2024/04/09 16:47:58 Scan status:  Running
2024/04/09 16:48:05 Scan status:  Running
2024/04/09 16:48:12 Scan status:  Running
2024/04/09 16:48:20 Scan status:  Running
2024/04/09 16:48:27 Scan status:  Running
2024/04/09 16:48:35 Scan status:  Running
2024/04/09 16:48:42 Scan status:  Running
2024/04/09 16:48:50 Scan status:  Running
2024/04/09 16:48:59 Scan status:  Running
2024/04/09 16:49:07 Scan status:  Running
2024/04/09 16:49:16 Scan status:  Running
2024/04/09 16:49:24 Scan status:  Running
2024/04/09 16:49:34 Scan status:  Running
2024/04/09 16:49:43 Scan Finished with status:  Completed
report option "scansummary" unavailable

**Comment by OrShamirCM** [comment]
Solved
